### ISSUE TITLE
Losing sound value after reboot

### ISSUE THREAD

**Issue by ben0a** [Sispheor/piclodio3#2]
I'm setting it up at around 80% but each time I reboot the pi, I'm back on default settings.

**Comment by Sispheor** [comment]
It's possible yes. The sound is handled by the OS. 
Actually, I've thought of this problem because the Clock radio should be always on.
Maybe you can try a [system command](http://raspberrypi.stackexchange.com/questions/13666/alsa-volume-lower-after-reboot) to store the value you want.
