### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by xMadNet** [Sispheor/piclodio3#20]
Hi
First install  (using your install modop)
My config : Linux XPi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
but
----
 sudo docker-compose up -d
WARNING: The PWD variable is not set. Defaulting to a blank string.
piclodio3_backend_1 is up-to-date
Starting piclodio3_frontend_1 ...
Starting piclodio3_frontend_1 ... error

ERROR: for piclodio3_frontend_1  Cannot start service frontend: driver failed programming external connectivity on endpoint piclodio3_frontend_1 (dcaee570d8bdd443ee38b8daae61b76026e4775068b1abadd691f8d6f7580ac7): Bind for 0.0.0.0:80 failed: port is already allocated

ERROR: for frontend  Cannot start service frontend: driver failed programming external connectivity on endpoint piclodio3_frontend_1 (dcaee570d8bdd443ee38b8daae61b76026e4775068b1abadd691f8d6f7580ac7): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

-

**Comment by Sispheor** [comment]
80 failed: port is already allocated
You already have a web server listening.
