### ISSUE TITLE
rpi date wrong

### ISSUE THREAD

**Issue by suypportedox** [Sispheor/piclodio3#3]
Hello

The rpi date is wrong on my piclodio webpage.   Piclodio display the UTC time and not the local time of my PI3

**Comment by Sispheor** [comment]
Indeed. same for me. I'll take a look into this.

**Comment by Sispheor** [comment]
Hi, I forgot that the Django framework need a setting for the timezone.
Please update [this line](https://github.com/Sispheor/piclodio3/blob/master/back/piclodio3/settings.py#L113) with your timezone and restart the backend.

E.g: `TIME_ZONE = 'Europe/Paris'`
