### ISSUE TITLE
Where to setup usb audio

### ISSUE THREAD

**Issue by ben0a** [Sispheor/piclodio3#4]
Hi Nicolas,

First, thank you for this excellent piece of software.
I want to move from default raspberry sound card, because the sound is awful most of the time. (tons of noise and saturation). I bought and setup an usb audio card. So I have alsa and a usb sound card correctly setup.

speaker-test -c2

Works perfectly well and sending a sound in command line too.
The problem is that picolodio is looking like this now:

<img width="874" alt="par defaut 2017-07-07 a 21 02 33" src="https://user-images.githubusercontent.com/1052696/27972732-a42c9c8a-6357-11e7-8e86-31334f9ab8d4.png">

Can you tell me where i can explain to piclodio which sound card to use?

Thanks

**Comment by Sispheor** [comment]
Piclodio use the default card of the Pi. So if the card is set as default output it should work perfectly.

**Comment by ben0a** [comment]
You are right. It seems i had tweaked the distribution a bit too much. So started back from the image you are providing. Just had to change .asoundrc in pi home folder to point to my usb card instead. It works far better now. Thanks!!

**Comment by Sispheor** [comment]
Good job!
You can leave here you're config/procedure to setup this if you want. I'll add it to the readme. It may help other users.
