### ISSUE TITLE
Create and open a Systemd service file for Gunicorn

### ISSUE THREAD

**Issue by pajeffery** [Sispheor/piclodio3#6]
Thanks for creating this, its just what I'm looking for.
I'm following the instructions to setup the backend on a fresh Raspbian Jessie build

I've created the gunicorn.service file in /etc/systemd/system/ and used the exact code in the instructions.

Running "sudo systemctl start gunicorn" causes an error
"Failed to start gunicorn.service: Unit gunicorn.service failed to load: Invalid argument. See system logs and 'systemctl status gunicorn.service' for details."

/var/log/sys shows
[/etc/systemd/system/gunicorn.service:9] Executable path is not absolute, ignoring: gunicorn --bind 0.0.0.0:8000 piclodio3.wsgi:application

 gunicorn.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Sispheor** [comment]
Give it an absolute path then.
