### ISSUE TITLE
Upgrade nodejs version + angular

### ISSUE THREAD

**Issue by stimulee** [Sispheor/piclodio3#8]
Hello

I tried to install Piclodio3 on Raspbian with a recent version of nodejs, but I have some issues on dependances. I tried to downgrade nodejs to 6.1 as requierement ask to, but now angular CLI ask for nodejs  >= 10.13.

So is there a way to upgrade nodejs requiered version in Piclodio3 to match current nodejs version?

Regards.

**Comment by Sispheor** [comment]
Actually I should upgrade the whole project to use last Raspbian / Angular / Python and Django.
And by the way implementing pending issues.
I will try to find some time to do this.

**Comment by stimulee** [comment]
Ok.
I already use the back part of your project to create a standalone alarm clock..
APIs works very fine, then thank you for the good job.
I hope you'll find time soon for upgrading the code, cause it will be fine to manage the alarm clock with the UI too ;-)
Thanks

**Comment by Sispheor** [comment]
I'm on it. Should takes 2 or 3 weeks.

**Comment by Sispheor** [comment]
Done
